config/routes.rb
Rails.application.routes.draw do
  
  get 'hotspot/images'

  resources :collections do
    delete '/unassign_product', to: "collections#unassign_product"
    post '/assign_product', to: "collections#assign_product"
    post '/update_collection_image', to: 'collections#update_collection_image'
    delete '/delete_image', to: 'collections#delete_image'
    post '/assign_hotspot_image', to: 'collections#assign_hotspot_image'
  end
  
  resources :interfaces
  resources :hotspot_images
  
  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end
  
  root :to => 'collections#index'
  

end

app/controllers/collections_controller.rb
class CollectionsController < AuthenticatedController
  require 'base64'
  skip_before_action :verify_authenticity_token
  def index
    @collections = ShopifyAPI::CustomCollection.all
    @interfaces = Interface.all
    @hotspot_images = HotspotImage.all
  end 
  
  def new
    @collection = ShopifyAPI::CustomCollection.new
  end
  
  def edit
    @collection = ShopifyAPI::CustomCollection.find(params[:id])
    @interfaces = Interface.all
    @interfaces_and_hotspot_images =  HotspotImage.select("hotspot_images.id as hotspot_image_id, hotspot_images.title as hotspot_image_title, interfaces.id as interface_id, interfaces.title as interface_title")
                                                  .joins("inner join collections_hotspot_images on collections_hotspot_images.collection_id = #{ @collection.id } and hotspot_images.id = collections_hotspot_images.hotspot_image_id")
                                                  .joins("right join interfaces on collections_hotspot_images.interface_id = interfaces.id").uniq
    @all_hotspot_images = HotspotImage.all
    @collection_products = @collection.products
    @product_builder_collection = ShopifyAPI::SmartCollection.where(:title => "Product_builder_products")[0]
    @all_products = ShopifyAPI::Product.find(:all, :params => { :limit => 250, :collection_id => @product_builder_collection.id})
    begin 
      @collection_image_src = @collection.image.src
    rescue
      @collection_image_src = ""
    end
  end
  
  def create
    if params[:commit] == 'Back to all collections'
      redirect_to root_url(:protocol => 'https')
      return true
    end
    
    @collection = ShopifyAPI::CustomCollection.new(collection_params)
    if @collection.save
      redirect_to root_url(:protocol => 'https')
    end
  end
  
  def update
    if params[:commit] == 'Back to all collections'
      redirect_to root_url(:protocol => 'https')
      return true
    end
    
    @collection = ShopifyAPI::CustomCollection.find(params[:id])
    @collection_products = @collection.products

    respond_to do |format|
      format.html do 
        if @collection.update_attributes(collection_params)
          redirect_to root_url(:protocol => 'https')
        end
      end
    end
  end
  
  def destroy
    @collection = ShopifyAPI::CustomCollection.find(params[:id])
    if @collection.destroy
      redirect_to root_url(:protocol => 'https')
    end
  end
  
  def unassign_product
    @collect = ShopifyAPI::Collect.where(product_id: params[:product_id], collection_id: params[:collection_id])[0]
    if @collect.destroy
      render json: { message: "unassigned" }, status: 200
    end
  end
  
  def assign_product
    @collect = ShopifyAPI::Collect.new(product_id: params[:product_id], collection_id: params[:collection_id])
    @product = ShopifyAPI::Product.find(params[:product_id])
    @product_image_source = ""
    unless @product.image.nil?
      @product_image_source = @product.image.src
    end
    if @collect.save
      render json: { product_title: @product.title, product_image_src: @product_image_src }, status: 200
    else
      render json: { message: "failed" }, status: 500
    end
  end
  
  def assign_hotspot_image
    @interface = Interface.find(params[:interface_id])
    current_collections_count = CollectionsHotspotImage.where(interface_id: @interface.id).count
    if @interface.collections_limit_count == current_collections_count 
      render json: { message: "Can't assign image to this interface because collections limit(#{ @interface.collections_limit_count }) in this interface was reached" }, status: 500
      return
    end
    @hotspot_image = HotspotImage.find(params[:hotspot_image_id])
    @collection = ShopifyAPI::CustomCollection.find(params[:collection_id])
    @collection_hotspot_image = CollectionsHotspotImage.find_by(collection_id: @collection.id, hotspot_image_id: @hotspot_image.id) || CollectionsHotspotImage.create(collection_id: @collection.id, hotspot_image_id: @hotspot_image.id)
    if @collection_hotspot_image.update_attributes(interface_id: @interface.id)
      render json: { message: "assigned" }, status: 200
    else 
      render json: { message: "failed" }, status: 500
    end
  end
  
  def delete_image
    @collection = ShopifyAPI::CustomCollection.find(params[:collection_id])
    if @collection.update_attributes(:image => "")
      render json: { message: "deleted" }, status: 200
    else
      render json: { message: "failed" }, status: 500
    end
  end
  
  def update_collection_image
    @collection = ShopifyAPI::CustomCollection.find(params[:collection_id])
    attachment = attachment = Base64.encode64(params[:image].tempfile.read)
    if @collection.update_attributes(image: { attachment: attachment })
      render json: { message: "unassigned" }, status: 200
    else
      render json: { message: "failed" }, status: 500
    end
  end
  
  private

    def collection_params
      params.permit(:body_html, :title)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_hotspot_images.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<div class="hotspot_images_listing">
  <div class="row">
    <div class="col-md-4">
      <strong>Hotspot Image Title</strong>
    </div>
    <div class="col-md-4">
      <strong>Delete Hotspot Image</strong>
    </div>
  </div>  
  <% @hotspot_images.each do |hotspot_image| %>
  <div class="row hotspot_image_row">
    <div class="col-md-4">
      <%= link_to hotspot_image.title, edit_hotspot_image_url(protocol: 'https', id: hotspot_image.id) %>
    </div>
    <div class="col-md-4">
      <%= link_to "Delete", hotspot_image_url(protocol: 'https', id: hotspot_image.id), :method => :delete, :confirm => "Are you sure you want to delete this hotspot image?" %>
    </div>
  </div>
  <% end %>
</div>
<%= link_to "Add New Hotspot Image", new_hotspot_image_url(protocol: 'https'), class: "btn btn-primary" %>

app/views/collections/_interfaces.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<div class="interfaces_listing">
  <div class="row">
    <div class="col-md-4">
      <strong>Interface Title</strong>
    </div>
    <div class="col-md-4">
      <strong>Delete Interface</strong>
    </div>
  </div>  
  <% @interfaces.each do |interface| %>
  <div class="row interface_row">
    <div class="col-md-4">
      <%= link_to interface.title, edit_interface_url(protocol: 'https', id: interface.id) %>
    </div>
    <div class="col-md-4">
      <%= link_to "Delete", interface_url(protocol: 'https', id: interface.id), :method => :delete, :confirm => "Are you sure you want to delete this interface?" %>
    </div>
  </div>
  <% end %>
</div>
<%= link_to "Add New Interface", new_interface_url(protocol: 'https'), class: "btn btn-primary" %>

app/views/collections/edit.html.erb
<style>
  .dz-error-message {
    display: none;  
  }
  .dz-success-mark {
    display: none;  
  }
  .dz-error-mark {
    display: none;  
  }
  .dz-image img {
    width: 135px !important;
  }
  .dz-preview {
    display: inline-block;
  }
  .dz-details {
    display: none;
  }
  .dz-progress {
    display: none;
  }
</style>
<script type="text/javascript">
//collection image dropzone
$(document).ready(function(){
  Dropzone.autoDiscover = false;
  $("#collection-image").dropzone({
    url: "<%= collection_update_collection_image_url(:collection_id => @collection.id, :protocol => 'https') %>",
    maxFilesize: 1,
    paramName: "image",
    previewsContainer: '.dropzone-previews',
    clickable: '.dropzone-previews',
    addRemoveLinks: true,
    success: function(file, response){
      if ( $('.dropzone-previews').find('.dz-preview').length === 2) {
        $('.dropzone-previews').find('.dz-preview:first').remove();
      }
      $('.dz-remove').click(function(){
        $.ajax({
         type: 'POST',
           data: { _method: 'DELETE' },
          url: '<%= collection_delete_image_url(collection_id: @collection.id, protocol: "https") %>',
          success: function(data){
            console.log(data.message);
          }
        });
      })
    },
    init: function(){
      <% unless @collection_image_src == "" %>
      var existingFiles = [];
      existingFiles.push({ id: "<%= @collection.id %>"});
      this.emit("addedfile", existingFiles[0]);
      this.emit("thumbnail", existingFiles[0], "<%= @collection_image_src %>");
      <% end %>
    }
		
  });	
	
  $('.dz-remove').click(function(){
    $.ajax({
      type: 'POST',
      data: { _method: 'DELETE' },
      url: '<%= collection_delete_image_url(collection_id: @collection.id, protocol: "https") %>',
      success: function(data){
        console.log(data.message);
      }
    });
  })
	
});
  
</script>

<script>
  $(document).ready(function(){
    $('.unassign_product').click(function(){
      var this_product_row = $(this).parents(".product_row");
      var product_id = $(this).data("product_id");
      var product_title = this_product_row.find('.product_title').text();
      $.ajax({
        url: "<%= collection_unassign_product_url(protocol: 'https', collection_id: @collection.id) %>",
        method: "POST",
        data: {
          product_id: product_id,
          _method: "DELETE"
        },
        success: function(){
          $('<option value="' + product_id + '">' + product_title + '</option>').appendTo('#add_products');
          this_product_row.remove();
        }
      })
    })
    
    /*var availableProducts = [
      <% @all_products.each do |product| %>
      '<%= product.title %>',
      <% end %>
    ];
    $("#add_products").autocomplete({
      source: availableProducts
    });*/
    $('.add_product_to_collection').click(function(e){
      e.preventDefault();
      var product_id = $('.select_product').val();
      $.ajax({
        url: '<%= collection_assign_product_url(collection_id: @collection.id, protocol: 'https') %>',
        method: 'POST',
        data: {
          product_id: product_id
        },
        success: function(product_info){
          var product_title = product_info.product_title;
          var product_image_src = product_info.product_image_src;
          var product_image_tag;
          if ((product_image_src != null) && (product_image_src != undefined) && (product_image_src != "")) {
            product_image_tag = '<img src="' + product_image_src + '">'
          } else {
            product_image_tag = ''
          }
          $('.select_product').find('option[value="' + product_id + '"]').remove();
          $('<div class="col-md-12 product_row">' +
              '<div class="col-md-2 col-lg-2 product_title">' + product_title + '</div>' +
              '<div class="col-md-2 col-lg-2 text-center">' + product_image_tag +
              '</div>' +
              '<div class="col-md-1 col-lg-1 text-center unassign_product" data-product_id="' + product_id + '"><strong>X</strong></div>' +
            '</div>').appendTo('.products_container');
          $('.unassign_product:last').click(function(){
            var this_product_row = $(this).parents(".product_row");
            var product_id = $(this).data("product_id");
            $.ajax({
              url: "<%= collection_unassign_product_url(protocol: 'https', collection_id: @collection.id) %>",
              method: "POST",
              data: {
                product_id: product_id,
                _method: "DELETE"
              },
              success: function(){
                $('<option value="' + product_id + '">' + product_title + '</option>').appendTo('#add_products');
                this_product_row.remove();
              }
            })
          })
        }
      })
    });
    
    $('.assign_hotspot_image').click(function(e){
      e.preventDefault();
      var interface_row = $(this).parents('.interface_row');
      clicked_select_image = interface_row.find('.select_hotspot_image');
      var hotspot_image_id = clicked_select_image.val();
      var interface_id = interface_row.data('interface_id');
      $.ajax({
        url: "<%= collection_assign_hotspot_image_url(protocol: 'https', collection_id: @collection.id) %>",
        method: "POST",
        data: {
          interface_id: interface_id,
          hotspot_image_id: hotspot_image_id,
        },
        success: function(){
          alert("success")
        },
        error: function(e){
          console.log(e);
          alert(e.responseJSON.message);
          clicked_select_image.val("0")
        }
      })
    });
    
    var select_image;
    <% @interfaces_and_hotspot_images.each do |interface_and_hotspot_image| %>
    select_image = $('.interface_row[data-interface_id="' + <%= interface_and_hotspot_image.interface_id %> + '"]').find('.select_hotspot_image');
    select_image.val('<%= interface_and_hotspot_image.hotspot_image_id.nil? ? "0" : interface_and_hotspot_image.hotspot_image_id  %>')
    <% end %>
  });
</script>
<div class="container">
  <%= form_tag collection_path, method: "patch", :html => { :controller => "collections", :action => "update", :id => @collection.id } do %>

  <div class="row">
    <div class="col-md-2">
      <%= submit_tag "Back to all collections", :class => "btn btn-info" %>
    </div>
  </div><br>

  <div class="row">
    <div class="col-md-8 form-group">
      <%= label_tag 'collection[title]', "Collection title:" %>
      <%= text_field_tag :title, @collection.title, class: "form-control" %>  
    </div>
    
    <div class="col-md-4 images_container pull-right">
      <h2>Featured Image</h2>
      <div class="dropzone-previews dropzone"> 
        <div class="dz-default dz-message"><span>Drop files here to upload</span>
        </div>
      </div>  
    </div>
    
    <div class="col-md-8 form-group">
      <%= label_tag 'collection[body_html]', "Collection description:" %>
      <%= text_area_tag :body_html, @collection.body_html, class: "tinymce form-control" %>
      <script> 
      //<![CDATA[
        (function() {
          if (typeof tinyMCE != 'undefined') {
            tinyMCE.init({
              selector: "textarea.tinymce",
              statusbar: false,
              menubar: false,
              resize: false,
              setup: function (editor) {
                editor.on('change', function (e) {  
                  enable_save();
                });
              },
              theme: "modern",
              fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt",
              font_formats: "Andale Mono=andale mono,times;"+
              "Arial=arial,helvetica,sans-serif;"+
              "Arial Black=arial black,avant garde;"+
              "Book Antiqua=book antiqua,palatino;"+
              "Comic Sans MS=comic sans ms,sans-serif;"+
              "Courier New=courier new,courier;"+
              "Georgia=georgia,palatino;"+
              "Helvetica=helvetica;"+
              "Impact=impact,chicago;"+
              "Symbol=symbol;"+
              "Tahoma=tahoma,arial,helvetica,sans-serif;"+
              "Terminal=terminal,monaco;"+
              "Times New Roman=times new roman,times;"+
              "Trebuchet MS=trebuchet ms,geneva;"+
              "Verdana=verdana,geneva;"+
              "Webdings=webdings;"+
              "Wingdings=wingdings,zapf dingbats; Open Sans='Open Sans', sans-serif;Playfair Display='Playfair Display', serif;",
              toolbar: ["undo redo | removeformat bold italic underline | fontsizeselect | forecolor backcolor | fontselect | letterspacing | lineheight"],
              plugins: "textcolor"
            });
          } else {
            setTimeout(arguments.callee, 50);
          }
        })();
      //]]>
      </script>      
    </div>
 
  </div>
  
  <div class="products_container row">
    <div class="col-md-12">
      <div class="col-md-2 col-lg-2"><strong>Product Title</strong></div>
      <div class="col-md-2 col-lg-2 text-center"><strong>Image</strong></div>
      <div class="col-md-1 col-lg-1 text-center"><strong>Unassign product from collection</strong></div>
    </div>
    <div class="col-md-3">
      <label>Add products: </label>
      <select class="select_product form-control" id="add_products">
        <option value=0>-Select product-</option>
        <% @all_products.each do |product| %>
          <% unless @collection_products.include? product %>
          <option value="<%= product.id %>"><%= product.title %></option>
          <% end %>
        <% end %>
      </select>
    </div>
    <div class="col-md-2">
      <br>
      <button class="add_product_to_collection btn btn-primary">
        Add Product
      </button>
    </div>
    <% @collection_products.each do |product| %>
      <div class="col-md-12 product_row">
        <div class="col-md-2 col-lg-2 product_title"><%= product.title %></div>
        <div class="col-md-2 col-lg-2 text-center">
          <%= img_tag product.image.src unless product.image.nil? %>
        </div>
        <div class="col-md-1 col-lg-1 text-center unassign_product" data-product_id="<%= product.id %>"><strong>X</strong></div>
      </div>
    <% end %>
  </div>
  
  <div class="row">
    <h3>Interfaces</h3>
    <% @interfaces.each do |interface| %>
      <div class="col-md-12 interface_row" data-interface_id="<%= interface.id %>">
        <div class="col-md-2">
          <%= interface.title %>  
        </div>
        <div class="col-md-4">
          <select class="form-control select_hotspot_image">
            <option value="0">
              -Select Hotspot Image-
            </option>
            <% @all_hotspot_images.each do |hotspot_image| %>
            <option value="<%= hotspot_image.id %>">
              <%= hotspot_image.title %>
            </option>
            <% end %>
          </select>
        </div>
        
        <div class="col-md-4">
          <button class="assign_hotspot_image btn btn-info">
            Assign Hotspot Image
          </button>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= submit_tag "Save collection information", :class => "btn btn-success" %>
    </div>
  </div>
  
  <% end %>
</div>

<form id="collection-image" action="" method="post" name="collection-image-dropzone">
  <input id="image" style="display:none;" name="image" type="file">
</form>

app/views/collections/index.html.erb
   
<div class="container">
  <div id="tabs">
    <ul>
      <li><a href="#tabs-1">All Collections</a></li>
      <li><a href="#tabs-2">Interfaces</a></li>
      <li><a href="#tabs-3">Hotspot Images</a></li>
    </ul>
    <div id="tabs-1" class="collections_listing">      
      <h3>All Collections</h3>
      <div class="row collections_row">
        <div class="col-md-2 col-lg-2"><strong>Collection Title</strong></div>
        <div class="col-md-2 col-lg-2 text-center"><strong>Image</strong></div>
        <div class="col-md-3 col-lg-3"><strong>Description</strong></div>
        <div class="col-md-1 col-lg-1 text-center"><strong>Delete?</strong></div>
        
      </div>
      <% @collections.each do |collection| %>
        <div class="row collections_row">
          <div class="col-md-2 col-lg-2">
            <%= link_to collection.title, edit_collection_url(:id => collection.id, :protocol => 'https', :collection_type => collection.class) %> 
          </div>
          <div class="col-md-2 col-lg-2 text-center">
            
          </div>
          <div class="col-md-3 col-lg-3" style="height:150px; overflow:hidden;">
            <%= render :html => collection.body_html.html_safe unless collection.body_html.nil? %>
          </div>
          
          <div class="col-md-1 col-lg-1 text-center">
            <%= link_to 'Delete', collection_url(collection.id, :protocol => 'https'), 
                { :method => :delete, class: "btn btn-danger",
                data: { confirm: 'Are you sure, you want to delete this collection?' } } %> 
          </div>
        </div>
      <% end %>
      <%= link_to "Create New Collection", new_collection_path, :class => "btn btn-primary" %>        
    </div>
    <div id="tabs-2">
      <%= render 'interfaces' %>
    </div>
    <div id="tabs-3">
      <%= render 'hotspot_images' %>
    </div>
  </div>
</div>

app/views/collections/new.html.erb
<div class="container">
  <%= form_tag collections_url(:protocol => 'https'), method: "post" do %>

  <div class="row">
    <div class="col-md-2">
      <%= submit_tag "Back to all collections", :class => "btn btn-info" %>
    </div>
  </div><br>

  <div class="row">
    <input type="hidden" name="collection_type" value="<%= @collection.class %>">
    <div cilass="col-md-12 form-group">
      <%= label_tag 'collection[title]', "Collection title:" %>
      <%= text_field_tag :title, nil, class: "form-control" %>  
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 form-group">
      <%= label_tag 'collection[body_html]', "Collection description:" %>
      <%= text_area_tag :body_html, nil, class: "tinymce form-control" %>
      <script> 
      //<![CDATA[
        (function() {
          if (typeof tinyMCE != 'undefined') {
            tinyMCE.init({
              selector: "textarea.tinymce",
              statusbar: false,
              menubar: false,
              resize: false,
              setup: function (editor) {
                editor.on('change', function (e) {  
                  enable_save();
                });
              },
              theme: "modern",
              fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt",
              font_formats: "Andale Mono=andale mono,times;"+
              "Arial=arial,helvetica,sans-serif;"+
              "Arial Black=arial black,avant garde;"+
              "Book Antiqua=book antiqua,palatino;"+
              "Comic Sans MS=comic sans ms,sans-serif;"+
              "Courier New=courier new,courier;"+
              "Georgia=georgia,palatino;"+
              "Helvetica=helvetica;"+
              "Impact=impact,chicago;"+
              "Symbol=symbol;"+
              "Tahoma=tahoma,arial,helvetica,sans-serif;"+
              "Terminal=terminal,monaco;"+
              "Times New Roman=times new roman,times;"+
              "Trebuchet MS=trebuchet ms,geneva;"+
              "Verdana=verdana,geneva;"+
              "Webdings=webdings;"+
              "Wingdings=wingdings,zapf dingbats; Open Sans='Open Sans', sans-serif;Playfair Display='Playfair Display', serif;",
              toolbar: ["undo redo | removeformat bold italic underline | fontsizeselect | forecolor backcolor | fontselect | letterspacing | lineheight"],
              plugins: "textcolor"
            });
          } else {
            setTimeout(arguments.callee, 50);
          }
        })();
      //]]>
      </script>      
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= submit_tag "Save collection information", :class => "btn btn-success" %>
    </div>
  </div>
  
  <% end %>
</div>